# Generated by Django 3.2 on 2021-04-07 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Giver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(choices=[('HP', 'History and Physical'), ('PD', 'Prioritize Differential Diagnosis'), ('RI', 'Recommend and Interpret Tests'), ('PH', 'Perform Handover'), ('PP', 'Perform Procedure')], default='HP', max_length=255)),
                ('complex', models.BooleanField(default=False)),
                ('complicated', models.BooleanField(default=False)),
                ('entrustability', models.IntegerField(choices=[(1, 'I did it.'), (2, 'I talked them through it.'), (3, 'I directed them from time to time.'), (4, 'I was available just in case.')], default=1)),
                ('done_well', models.TextField()),
                ('needs_improvement', models.TextField()),
                ('feedbackDate', models.DateTimeField(auto_now_add=True)),
                ('giver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.giver')),
            ],
        ),
    ]
